name: 'WPS Work'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '30 2 * * *'

jobs:
  daily_check_in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working-invite'
        env:
          USERID: ${{ secrets.USERID }} #接收邀请用户ID
          SIDS: ${{ secrets.SIDS }} # 邀请账号SID
          STMP_SERVER: ${{ secrets.STMP_SERVER }} # STMP服务器
          FROM_ADDR: ${{ secrets.FROM_ADDR }} # 发件邮箱
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }} # 邮箱密码或邀请码
          TO_ADDR: ${{ secrets.TO_ADDR }} # 收件邮箱
          wps_sid: ${{ secrets.wps_sid }} # 签到账号SID

        run: |
          python WPS_accept_invitation.py
          python docer_check_in.py
#       - name: 'Working-signin'
#         env: 
#            WPS_SID: ${{secrets.WPS_SID}}
#         run: python WPS_sign_in.py
